name: RPM Build

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master


jobs:
  build-rpm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    # Custom rpm building from Derek
    - uses: djw8605/docker-mock-rpmbuilder@master
      with:
        spec-file: rpm/scitokens-cpp.spec

      
