name: RPM Build

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master


jobs:
  build-rpm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Build RPM
      uses: mmornati/docker-mock-rpmbuilder@master
      env:
        SPEC_FILE: "rpm/scitokens-cpp.spec"
        SOURCES: workspace
      
